apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyhostnamespace
spec:
  crd:
    spec:
      names:
        kind: K8sDenyHostNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyhostnamespace

        violation[{"msg": msg}] {
          input.review.object.spec.hostNetwork == true
          msg := "Host network access denied"
        }

        violation[{"msg": msg}] {
          input.review.object.spec.hostPID == true
          msg := "Host PID namespace access denied"
        }

        violation[{"msg": msg}] {
          input.review.object.spec.hostIPC == true
          msg := "Host IPC namespace access denied"
        }
